scrape_configs:
  - job_name: prometheus
    scrape_interval: 30s
    static_configs:
      - targets: ['localhost:9090']
        labels:
          group: 'prometheus'
#  - job_name: watchtower-docker
#    scrape_interval: 10m
#    metrics_path: /v1/metrics
#    bearer_token:   # your API_TOKEN
#    static_configs:
#      - targets: ['watchtower:8080']
  - job_name: node-docker
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus-node:9100']
  - job_name: cadvisor-docker
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus-cadvisor:8080']
  - job_name: snmp-docker
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.50.6']  # your NAS-IP
    metrics_path: /snmp
    params:
      module: [synology]
      auth: [snmpv3]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: [__param_target]
        regex: (.*)
        replacement: prometheus-snmp:9116
        target_label: __address__
